name: Check scalafmt on push
on:
  pull_request:
    types: [opened, reopened]

jobs:
  scalafmt-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checking your code to see if u r naughty or nice
        uses: openlawteam/scalafmt-ci@v2
        with:
          args: "--exclude=third_party --list"

